name: Blocks Playwright Tests

on:
    pull_request:
        paths:
            - '.github/workflows/blocks-playwright.yml' # This file
            - 'plugins/woocommerce-blocks/**'
            - 'plugins/woocommerce/src/Blocks/**'
            - 'plugins/woocommerce/templates/**'
            - 'plugins/woocommerce/patterns/**'
    # Allow manually triggering the workflow.
    workflow_dispatch:

env:
    FORCE_COLOR: 1

jobs:
    blocks-playwright-tests:
        name: Playwright E2E tests
        timeout-minutes: 60
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: plugins/woocommerce-blocks

        steps:
            - uses: actions/checkout@v4

            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo
              with:
                  install: '@woocommerce/plugin-woocommerce...'
                  build: '@woocommerce/plugin-woocommerce'

            - name: Install Playwright dependencies
              run: pnpm exec playwright install chromium --with-deps

            - name: Setup testing environment and start the server
              run: pnpm env:start

            - name: Run Playwright tests
              run: pnpm test:e2e

            - name: Archive debug artifacts (screenshots, traces)
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: failures-artifacts-shard
                  path: plugins/woocommerce-blocks/tests/e2e/artifacts/test-results
                  if-no-files-found: ignore

            - name: Archive flaky tests report
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: flaky-tests-report
                  path: plugins/woocommerce-blocks/flaky-tests
                  if-no-files-found: ignore

    merge-artifacts:
        # Merges all artifacts from all shards into a single zip and
        # deletes the parts. In case of a rerun, artifacts from the
        # previous run will be retained by merging them with the new ones.
        name: Merge Artifacts
        if: ${{ !cancelled() }}
        needs: [blocks-playwright-tests]
        runs-on: ubuntu-latest
        steps:
            - name: Merge Artifacts
              uses: actions/upload-artifact/merge@v4
              # Don't fail the job if there aren't any artifacts to merge.
              continue-on-error: true
              with:
                  name: failures-artifacts
                  pattern: failures-artifacts*
                  delete-merged: true

            - name: Merge flaky tests reports
              id: merge-flaky-tests-reports
              uses: actions/upload-artifact/merge@v4
              continue-on-error: true
              with:
                  name: flaky-tests-report
                  pattern: flaky-tests-report*
                  delete-merged: true
